### ISSUE TITLE
Not working with AdGuard or Opera built-in adblocker

### ISSUE THREAD

**Issue by jonata** [clemdesign/grav-plugin-detect-adblock#2]
Hi, thanks for the update v2.0.3. I'm still not able to get it working. I tested with Firefox (Adguard) and Opera built-in adblocker. I see the code on `body`, but the div layers have the `display: none` property.

**Comment by clemdesign** [comment]
This plugin is based on https://www.detectadblock.com/ solution.
Maybe break changes append since last integration.
An analyze shall be done.
